//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WebApplication.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.WebApplication.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=127.0.0.1;Port=3306;Database=misa.web202302_mf1587_vqanh;Uid=vqanh;Pwd=12345678;.
        /// </summary>
        public static string connectionString {
            get {
                return ResourceManager.GetString("connectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an example.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không tìm thấy tài nguyên.
        /// </summary>
        public static string DevMsg_NotFound {
            get {
                return ResourceManager.GetString("DevMsg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string DevMsg_Validate {
            get {
                return ResourceManager.GetString("DevMsg_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ MISA!.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không tìm thấy tài nguyên.
        /// </summary>
        public static string UserMsg_NotFound {
            get {
                return ResourceManager.GetString("UserMsg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_Validate {
            get {
                return ResourceManager.GetString("UserMsg_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  này đã tồn tại.
        /// </summary>
        public static string Validate_CheckDuplicate {
            get {
                return ResourceManager.GetString("Validate_CheckDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string Validate_EmailMalformed {
            get {
                return ResourceManager.GetString("Validate_EmailMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vượt quá 100 ký tự.
        /// </summary>
        public static string Validate_Length100 {
            get {
                return ResourceManager.GetString("Validate_Length100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vượt quá 20 ký tự.
        /// </summary>
        public static string Validate_Length20 {
            get {
                return ResourceManager.GetString("Validate_Length20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vượt quá 25 ký tự.
        /// </summary>
        public static string Validate_Length25 {
            get {
                return ResourceManager.GetString("Validate_Length25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vượt quá 255 ký tự.
        /// </summary>
        public static string Validate_Length255 {
            get {
                return ResourceManager.GetString("Validate_Length255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vượt quá 50 ký tự.
        /// </summary>
        public static string Validate_Length50 {
            get {
                return ResourceManager.GetString("Validate_Length50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tháng năm vượt quá hiện tại.
        /// </summary>
        public static string Validate_TimeMalformed {
            get {
                return ResourceManager.GetString("Validate_TimeMalformed", resourceCulture);
            }
        }
    }
}
